### ISSUE TITLE
Описание проекта

### ISSUE THREAD

**Issue by Vaysman** [i-wanna-be-a-programmer/stealer#1]
В файле readme.mb опишите минимальный функционал проекта:
1. Интерфейс взаимодействия с пользователем (рекомендую консольный)
2. Минимальный набор функций
3. Примерная архитектура

**Comment by Burton777** [comment]
Готово!

**Comment by Vaysman** [comment]
Описание выглядит довольно неряшливо. Изучите [markdown](https://guides.github.com/features/mastering-markdown/) и справьте ошибки форматиртвания.

**Comment by Burton777** [comment]
Готово!

**Comment by Vaysman** [comment]
значительно лучше 🎉
